### ISSUE TITLE
Framework Malfunction Post-Install On User Input

### ISSUE THREAD

**Issue by hteokhtneubtnoet** [M4cs/DarkSpiritz#1]
Pulling the latest from M4cs/darkspiritz.git and installing per written instructions using `pip` appears to work correctly, producing no errors. However, starting DSPF with `python start.py` (or `./start.py`) produces unexpected output, especially when attempting to interact with the framework prompt:

```
('\x1b[34m\n      [15:44] Connected to a network.\n      [15:44] Local IP Address:', '10.0.2.99\x1b[0m')

      ██████╗   ███████╗  ██████╗   ███████╗
      ██╔══██╗  ██╔════╝  ██╔══██╗  ██╔════╝
      ██║  ██║  ███████╗  ██████╔╝  █████╗
      ██║  ██║  ╚════██║  ██╔═══╝   ██╔══╝
      ██████╔╝  ███████║  ██║       ██║
      ╚═════╝   ╚══════╝  ╚═╝       ╚═╝
      Dark  Spiritz  Penetesting  Framework
              Current Version: 2.0

      Developed by Syntel - @syndicatedintel
           https://syndicatedintel.com/

     Use help or ? to see available commands.

For support open an issue on GitHub or E-Mail Us here:
           syndicatedintel@protonmail.com

         [15:44] Loaded Configuration File

[DSPF]> ?
Traceback (most recent call last):
  File "start.py", line 202, in <module>
    main()
  File "start.py", line 84, in main
    terminal = input(terminalname + colors.END).lower()
  File "<string>", line 1
    ?
    ^
SyntaxError: unexpected EOF while parsing
root@kali:~/darkspiritz# 
```
Entering `help` similarly breaks DSPF:
```
('\x1b[34m\n      [15:47] Connected to a network.\n      [15:47] Local IP Address:', '10.0.2.99\x1b[0m')

      ██████╗   ███████╗  ██████╗   ███████╗
      ██╔══██╗  ██╔════╝  ██╔══██╗  ██╔════╝
      ██║  ██║  ███████╗  ██████╔╝  █████╗
      ██║  ██║  ╚════██║  ██╔═══╝   ██╔══╝
      ██████╔╝  ███████║  ██║       ██║
      ╚═════╝   ╚══════╝  ╚═╝       ╚═╝
      Dark  Spiritz  Penetesting  Framework
              Current Version: 2.0

      Developed by Syntel - @syndicatedintel
           https://syndicatedintel.com/

     Use help or ? to see available commands.

For support open an issue on GitHub or E-Mail Us here:
           syndicatedintel@protonmail.com

         [15:47] Loaded Configuration File

[DSPF]> help
Traceback (most recent call last):
  File "start.py", line 202, in <module>
    main()
  File "start.py", line 84, in main
    terminal = input(terminalname + colors.END).lower()
AttributeError: '_Helper' object has no attribute 'lower'
root@kali:~/darkspiritz# 
```

**Comment by M4cs** [comment]
I added some fixes could you try to pull the most recent source and tell me if the error persists?

**Comment by hteokhtneubtnoet** [comment]
Couldn't get back to you until today. I'm sorry.

The issue still persists identically to the parent comment.
